specVersion: 1.0.0
name: subquery-airdrop-project
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '>=1.18.0'
  query:
    name: '@subql/query'
    version: '>=1.10.0'
description: 'Query registry project for SubQuery Testnet'
repository: ''
schema:
  file: ./schema.graphql
network:
  chainId: '0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527' #moonbase alpha
  endpoint: 'wss://moonbeam-alpha.api.onfinality.io/public-ws'
  dictionary: 'https://api.subquery.network/sq/subquery/go-dict'
  chaintypes:
    file: ./dist/chaintypes.js

x-frontier: &frontier
  kind: substrate/FrontierEvm
  startBlock: 3759675
  processor: &frontier-processor
    file: './dist/frontierEvm.js'
  assets:
    airdropper:
      file: ./node_modules/@subql/contract-sdk/artifacts/contracts/Airdropper.sol/Airdropper.json

dataSources:
  - <<: *frontier
    processor:
      <<: *frontier-processor
      options:
        abi: airdropper
        address: '0xAA88e5E18176f903345462208f8E038B2cD04a37'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleRoundCreated
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - RoundCreated(uint256 indexed roundId, address tokenAddress, uint256 roundStartTime, uint256 roundDeadline)
        - handler: handleAddAirdrop
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - AddAirdrop(address indexed addr, uint256 roundId, uint256 amount)
        - handler: handleAirdropClaimed
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - AirdropClaimed(address indexed addr, uint256 roundId, uint256 amount)
        - handler: handleRoundSettled
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - RoundSettled(uint256 indexed roundId, address settleDestination, uint256 unclaimAmount)
